version: "2"

run:
  timeout: 30m
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
linters:
  enable:
  - bodyclose
  - dogsled
  - errcheck
  - copyloopvar
  - gocognit
  - goconst
  - gocritic
  - godox
  - gofmt
  - goimports
  #- gosec
  - gosimple
  - govet
  - ineffassign
  - nakedret
  #- revive
  - staticcheck
  #- stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - reassign
