version: "2"

run:
  timeout: 30m
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

formatters:
  enable:
    - gofmt
    - goimports

linters:
  enable:
  - bodyclose
  - dogsled
  - errcheck
  - copyloopvar
  - gocognit
  - goconst
  - gocritic
  - godox
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - reassign
