run:
  timeout: 30m
output:
  formats:
    - format: line-number
linters:
  disable-all: false
  enable:
  - bodyclose
  - dogsled
  - errcheck
  - copyloopvar
  - gocognit
  - goconst
  - gocritic
  - godox
  - gofmt
  - goimports
  #- gosec
  - gosimple
  - govet
  - ineffassign
  - nakedret
  #- revive
  - staticcheck
  #- stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - whitespace
  - reassign
