project_name: artifactory-resource

builds:
  - &build
    id: check
    main: ./check/main.go
    binary: 'assets_{{ .Os }}_{{ .Arch }}/check'
    no_unique_dist_dir: true
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
    goos: [linux]
    goarch: [amd64]
  - <<: *build
    id: in
    main: ./in/main.go
    binary: 'assets_{{ .Os }}_{{ .Arch }}/in'
  - <<: *build
    id: out
    main: ./out/main.go
    binary: 'assets_{{ .Os }}_{{ .Arch }}/out'

archives:
- format: binary

changelog:
  sort: asc
  use: github
  filters:
    exclude:
    - 'docs'
    - '\.md'

checksum:
  name_template: checksums.txt
  algorithm: sha256

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "orangeopensource/artifactory-resource:latest"
      - "orangeopensource/artifactory-resource:{{ .Tag }}"
      - "orangeopensource/artifactory-resource:v{{ .Major }}"
      - "orangeopensource/artifactory-resource:v{{ .Major }}.{{ .Minor }}"
    build_flag_templates:
      # https://github.com/opencontainers/image-spec/
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"

release:
  prerelease: auto
  name_template: '{{.Tag}}'
